# Add github config change label to any change of files in docs folder, or subfolders
github-config-change:
  - .github/**/*

# Add documentation change label for readme changes
documentation-change:
  - "*.md"
