name: 'Gradle - Build & Test'

on:
  workflow_call:
    inputs:
      minimum-coverage:
        required: false 
        default: 70
        type: number
jobs:
  gradle-build-test:
    name: : Gradle Build and Test 
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper

      - name: Execute Gradle build
        run: ./gradlew clean build

      - name: Upload Build Output
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: |
            build
            Dockerfile
            docker-compose.yml
            .dockerignore

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Publish Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.6
        with:
          coverage_results_path: 'build/reports/jacoco/test/jacocoTestReport.xml'
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: ${{inputs.minimum-coverage}}
          fail_below_threshold: true
          publish_only_summary: false
