name: "Send Metrics to Datadog"
# from https://github.com/int128/datadog-actions-metrics
on:
  pull_request:
    types:
      - opened
      - closed

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      pull-requests: read
    steps:
      - uses: int128/datadog-actions-metrics@e26cf98fccaf57bfb818f14f0d7324b9b98850f3
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          datadog-site: "datadoghq.eu"
