name: "Send Metrics to Datadog"

on:
  workflow_run:
    workflows:
      - '**'
    types:
      - completed
  pull_request:
    types:
      - opened
      - closed
      - edited
      - labeled

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      checks: read
      contents: read
    steps:
      - uses: int128/datadog-actions-metrics@d6765ffc8114e9d44cbfe53ac198df94486a0834
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          datadog-site: "datadoghq.eu"
          collect-job-metrics: true
          collect-step-metrics: true
          send-pull-request-labels: true
