name: "Send Metrics to Datadog"

on:
  pull_request:
    types:
      - opened
      - closed
      - edited
      - labeled

jobs:
  send:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      checks: read
      contents: read
      id-token: write
    steps:
      - uses: mononokehime/datadog-actions-metrics@v1.1.0
        with:
          # create an API key in https://docs.datadoghq.com/account_management/api-app-keys/
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }}
          datadog-site: "datadoghq.eu"
