name: 'Push to ECR'

on:
  workflow_call:
    inputs:    
      build-files:
        required: false 
        default: "build-files"
        type: string
      AWS_REGION:
        required: true
        type: string
      ECR_REGISTRY:
        required: true
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
    outputs:
      image-name: ${{ steps.build-image.outputs.image }}

jobs:

  push-to-ecr:
    runs-on: ubuntu-latest
    name: Push to ECR
    environment: development
    outputs:
      image: ${{ steps.build-image.outputs.image }}

    steps:
      - name: Download Build Output
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build-files}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          imageName=${{inputs.ECR_REGISTRY}}/${{inputs.ECR_REPOSITORY}}:${{inputs.IMAGE_TAG}}
          echo "Build and push $imageName"
          docker build -t ${{inputs.ECR_REGISTRY}}/${{inputs.ECR_REPOSITORY}}:${{inputs.IMAGE_TAG}} .
          docker push ${{inputs.ECR_REGISTRY}}/${{inputs.ECR_REPOSITORY}}:${{inputs.IMAGE_TAG}}
          echo "image=$imageName" >> $GITHUB_OUTPUT



