name: 'Push to ECR'

on:
  workflow_call:
    inputs:    
      build-files:
        required: false 
        default: "build-files"
        type: string
      aws-region:
        required: true
        type: string
      ecr-repository:
        required: true
        type: string
    outputs: 
      image-name:
        description: The image created in build-image
        value: ${{ jobs.push-to-ecr.outputs.image }}

jobs:

  push-to-ecr:
    runs-on: ubuntu-latest
    name: Push to ECR
    environment: development
    outputs:
      image: ${{ steps.build-image.outputs.image }}
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download Build Output
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build-files}}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          imageName=$ECR_REGISTRY}}/${{inputs.ecr-repository}}:$IMAGE_TAG
          echo "Build and push $imageName"
          docker build -t $ECR_REGISTRY/${{inputs.ecr-repostory:$IMAGE_TAG .
          docker push $ECR_REGISTRY/${{inputs.ecr-repository}}:$IMAGE_TAG
          echo "image=$imageName" >> $GITHUB_OUTPUT



