name: Release

on:
  pull_request:
    types:
      - closed

jobs:
  release:
    timeout-minutes: 2
    name: Tag and Release to github
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      release-number: ${{ steps.tag_and_release.outputs.tag }}
    permissions:
      id-token: write
      contents: read

    steps:
      # This will do a semver release based on patch,minor,major tags
      - name: Tag and Release to GH
        id: tag_and_release
        uses: K-Phoen/semver-release-action@1a1fc63a95a12b4bb535b53ab0d861bce53ce89d
        with:
          release_branch: main
          release_strategy: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-release:
    needs: [release]
    timeout-minutes: 2
    name: Output Release Version
    runs-on: ubuntu-latest
    steps:
      - name: test release output
        run: echo ${{needs.release.outputs.release-number}}
